name: Build and Deploy Kener Docker Image
on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-docker-images:
      name: Build and Publish Docker Image
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source code
          uses: actions/checkout@v3
          with:
            repository: rajnandan1/kener
        - name: Checkout source code
          uses: actions/checkout@v3
          with:
            clean: false
            sparse-checkout: |
              custom-docker
            sparse-checkout-cone-mode: false
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Log in to the Container registry
          uses: docker/login-action@v2
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Docker Metadata
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ${{env.REGISTRY }}/${{ env.IMAGE_NAME }}/kener
            tags: |
              type=sha
              latest
            labels: |
              maintainer=bisegni@slac.stanford.edu
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          id: build_and_push
          with:
            context: .
            file: ./custom-docker/KenerDockerfile
            push: true
            provenance: false
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              GH_USERNAME=${{ secrets.GH_PACKAGE_USERNAME }}
              GH_TOKEN=${{ secrets.GH_PACKAGE_TOKEN }}
              KENER_BASE_PATH=/status
            platforms: linux/amd64,linux/arm64